# Generated by Django 4.2.5 on 2023-09-26 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18, unique=True)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('genero', models.JSONField()),
                ('fecha_nacimiento', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('estado', models.JSONField()),
            ],
        ),
    ]
