# Generated by Django 4.2.5 on 2023-09-23 20:49

import Utiles.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Beneficiario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('genero', models.JSONField()),
                ('fecha_nacimiento', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('estado', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Escuela',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('clave', models.CharField(max_length=150)),
                ('turno', models.CharField(max_length=25)),
                ('colonia', models.CharField(max_length=150)),
                ('calle', models.CharField(max_length=150)),
                ('numero', models.CharField(max_length=100)),
                ('domicilio', models.CharField(max_length=200)),
                ('region', models.CharField(max_length=50)),
                ('zona_escolar', models.CharField(max_length=50)),
                ('clave_zona_escolar', models.IntegerField()),
                ('nivel', models.CharField(max_length=50)),
                ('subnivel', models.CharField(max_length=50)),
                ('control', models.CharField(max_length=50)),
                ('nombre_mostrar', models.CharField(max_length=500)),
                ('geom', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('genero', models.JSONField()),
                ('fecha_nacimiento', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('estado', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Tutor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18)),
                ('nombre', models.CharField(max_length=50)),
                ('primer_apellido', models.CharField(max_length=100)),
                ('segundo_apellido', models.CharField(max_length=100)),
                ('sexo', models.CharField(max_length=1)),
                ('genero', models.JSONField()),
                ('fecha_nacimiento', models.CharField(max_length=15)),
                ('edad', models.IntegerField()),
                ('estado', models.JSONField()),
            ],
        ),
        migrations.CreateModel(
            name='Paquete',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_entrega', models.IntegerField(default=Utiles.models.numero_random, unique=True)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('Beneficiario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario', to='Utiles.beneficiario')),
                ('funcionario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='Utiles.funcionario')),
                ('solicitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitante', to='Utiles.tutor')),
            ],
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escuela', to='Utiles.escuela'),
        ),
        migrations.AddField(
            model_name='beneficiario',
            name='tutor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tutor', to='Utiles.tutor'),
        ),
    ]
