# Generated by Django 4.2.5 on 2023-09-24 02:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Utiles', '0002_alter_beneficiario_tutor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='curp',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='beneficiario',
            name='escuela',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario_Escuela', to='Utiles.escuela'),
        ),
        migrations.AlterField(
            model_name='escuela',
            name='clave',
            field=models.CharField(max_length=150, unique=True),
        ),
        migrations.AlterField(
            model_name='funcionario',
            name='curp',
            field=models.CharField(max_length=18, unique=True),
        ),
        migrations.AlterField(
            model_name='tutor',
            name='curp',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
