# Generated by Django 4.2.5 on 2023-09-25 05:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Utiles', '0003_alter_beneficiario_curp_alter_beneficiario_escuela_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='beneficiario',
            name='escuela',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario_Escuela', to='Utiles.escuela'),
        ),
    ]
