# Generated by Django 4.2.5 on 2023-09-25 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Utiles', '0004_alter_beneficiario_escuela'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='Beneficiario',
            field=models.CharField(max_length=18, unique=True),
        ),
    ]
