# Generated by Django 4.2.5 on 2023-09-26 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Utiles', '0006_rename_beneficiario_paquete_beneficiario_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paquete',
            name='beneficiario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='beneficiario', to='Utiles.beneficiario'),
        ),
    ]
