# Generated by Django 4.2.5 on 2023-09-26 05:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Utiles', '0007_alter_paquete_beneficiario'),
    ]

    operations = [
        migrations.AddField(
            model_name='paquete',
            name='entregado',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='paquete',
            name='fecha_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='paquete',
            name='funcionario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='funcionario', to='Utiles.funcionario'),
        ),
    ]
